# Welcome to Jekyll!
#

# Site settings
title: Toutes Sportives
description: |
  Ufolep s'engage pour le sport féminin
owner: Ufolep # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: nvincent.laligue@ufolep-usep.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toutessportives.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/UFOLEP
  github: https://github.com/UFOLEP
  facebook-official: https://facebook.com/UFOLEP-Nationale-147227585324584/
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
sass:
  style: compressed
