# Welcome to Jekyll!
#

# Site settings
title: Toutes Sportives
description: |
  Ufolep s'engage pour le sport féminin
owner: Ufolep 
email: nvincent.laligue@ufolep-usep.fr
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ufolep.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/UFOLEP
  github: https://github.com/UFOLEP
  facebook-official: https://facebook.com/UFOLEP-Nationale-147227585324584/
# Build settings
markdown: kramdown
sass:
  style: compressed
